# Server port for the auth-service in the development environment
#server:
#  port: 8083

# Spring application name
spring:
#  application:
#    name: auth-service

  # Database connection settings for PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5001/auth_db
    username: admin_user
    password: password

  # JPA and Hibernate settings
  jpa:
    hibernate:
      # Automatically update the database schema on startup for development
      ddl-auto: update
    properties:
      hibernate:
        # Explicitly set the dialect for PostgreSQL
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # Format the SQL logs to be more readable
        format_sql: true
    # Show the generated SQL queries in the logs
    show-sql: true

# Eureka client configuration for service discovery
#eureka:
#  client:
#    # URL of the Eureka server
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#    # Fetch the registry information from the Eureka server
#    fetch-registry: true
#    # Register this instance with the Eureka server
#    register-with-eureka: true

# JWT (JSON Web Token) settings - replace with your actual secret and expiration
#jwt:
#  secret: 2f84ef2da9df36469b77e4046a9d9221f827f5b7707e8d37cf38aed5f8de9eee
#  expiration: 86400000 # 24 hours in milliseconds

logging:
  level:
    org.springframework.security: DEBUG
    com.chauhan.authservice: DEBUG

security:
  jwt:
    secret: ${JWT_SECRET:saiofal;vkasfbehwqpofhjashofjaswfpojasfvbafop[hfifonfo[shjfwefjjfslajfsahfoshffasnbash[f}
    issuer: ${JWT_ISSUER:api.substring.com}
    access-ttl-seconds: ${JWT_ACCESS_TTL_SECONDS:3000}
    refresh-ttl-seconds: ${JWT_REFRESH_TTL_SECONDS:86400}
    refresh-token-cookie-name: ${JWT_REFRESH_COOKIE_NAME:refreshToken}
    cookie-secure: ${JWT_COOKIE_SECURE:true}
    cookie-http-only: ${JWT_COOKIE_HTTP_ONLY:true}
    cookie-same-site: ${JWT_COOKIE_SAME_SITE:lax}
    cookie-domain: ${JWT_COOKIE_DOMAIN:localhost}